'use client';

import { useMemo, useState } from 'react';

type Tab = 'home' | 'apps' | 'activity' | 'help';
type App = { code:string; name:string; description:string; category:string; color:string; favorite:boolean; updated:string };

const initialApps: App[] = [
  {code:'YE',name:'Your Expense Manager',description:'Keep spending, budgets and monthly goals organized.',category:'Finance',color:'peach',favorite:true,updated:'Used today'},
  {code:'YH',name:'Your Household Manager',description:'Find and manage everything stored around your home.',category:'Home',color:'sky',favorite:true,updated:'Used yesterday'},
  {code:'FT',name:'Family Tree',description:'Explore your family connections, stories and shared history.',category:'Family',color:'violet',favorite:false,updated:'Used 4 days ago'},
  {code:'DR',name:'Dayaro Radio',description:'Listen to Gujarati music and community radio wherever you are.',category:'Media',color:'sage',favorite:false,updated:'Used last week'},
];

export default function UserPortal(){
  const [tab,setTab]=useState<Tab>('home'); const [apps,setApps]=useState(initialApps); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<App|null>(null); const [menu,setMenu]=useState(false);
  const visible=useMemo(()=>apps.filter(app=>app.name.toLowerCase().includes(query.toLowerCase())||app.category.toLowerCase().includes(query.toLowerCase())),[apps,query]);
  const toggleFavorite=(name:string)=>setApps(list=>list.map(app=>app.name===name?{...app,favorite:!app.favorite}:app));
  return <main className="user-portal">
    <header className="user-header"><button className="user-brand" onClick={()=>setTab('home')}><b>Y</b><span>YAM</span></button><nav aria-label="User navigation">{[['home','Home'],['apps','My apps'],['activity','Activity'],['help','Help']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as Tab)}>{label}</button>)}</nav><div className="user-tools"><button className="user-bell" aria-label="Notifications">●</button><button className="user-profile" onClick={()=>setMenu(!menu)}><span>JD</span><i><b>Jinal Donda</b><small>Family member</small></i><em>⌄</em></button>{menu&&<div className="profile-menu"><button>My profile</button><button>Preferences</button><button>Sign out</button></div>}</div></header>
    <div className="user-body">
      {tab==='home'&&<><section className="welcome"><div><p>YOUR YAM SPACE</p><h1>Welcome back, Jinal.</h1><span>Everything shared with you is ready when you are.</span></div><div className="date-card"><small>SATURDAY</small><strong>29</strong><span>August 2026</span></div></section><section className="quick-row"><div><span className="quick-icon">◷</span><p><b>Pick up where you left off</b><small>Your Household Manager · Kitchen inventory</small></p><button onClick={()=>setSelected(apps[1])}>Continue →</button></div><aside><i>✓</i><p><b>All systems available</b><small>Your apps are working normally</small></p></aside></section><UserSection title="Your favourites" label="QUICK ACCESS" action={<button onClick={()=>setTab('apps')}>View all apps →</button>}/><AppGrid apps={apps.filter(a=>a.favorite)} toggleFavorite={toggleFavorite} setSelected={setSelected}/><UserSection title="Recently used" label="CONTINUE EXPLORING"/><div className="recent-list">{apps.slice(0,3).map(app=><button key={app.name} onClick={()=>setSelected(app)}><span className={`mini-app ${app.color}`}>{app.code}</span><i><b>{app.name}</b><small>{app.updated}</small></i><em>→</em></button>)}</div></>}
      {tab==='apps'&&<><section className="user-page-title"><p>MY APPS</p><h1>Your shared workspace</h1><span>These are the projects Yagnik has made available to you.</span></section><div className="app-toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your apps"/></label><span>{visible.length} available apps</span></div><AppGrid apps={visible} toggleFavorite={toggleFavorite} setSelected={setSelected}/></>}
      {tab==='activity'&&<><section className="user-page-title"><p>YOUR ACTIVITY</p><h1>Recent moments</h1><span>A private history of the apps you have opened.</span></section><div className="user-timeline">{apps.map((app,i)=><article key={app.name}><span className={`mini-app ${app.color}`}>{app.code}</span><div><b>{i===0?'Expense added':i===1?'Inventory viewed':i===2?'Family profile opened':'Station played'}</b><p>{app.name}</p><small>{app.updated}</small></div></article>)}</div></>}
      {tab==='help'&&<><section className="user-page-title"><p>HELP CENTRE</p><h1>How can we help?</h1><span>Find answers or contact the YAM workspace owner.</span></section><div className="help-grid"><article><i>?</i><h2>Using your apps</h2><p>Learn how to open projects, save favourites, and find your recent work.</p><button>Read the guide →</button></article><article><i>♙</i><h2>Access questions</h2><p>Only the owner can give you access to additional YAM projects.</p><button>Contact Yagnik →</button></article><article><i>⌘</i><h2>Privacy & security</h2><p>Understand how your personal activity and shared information are protected.</p><button>Learn more →</button></article></div></>}
    </div>
    {selected&&<div className="user-modal-bg" onMouseDown={()=>setSelected(null)}><section className="user-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setSelected(null)}>×</button><div className={`large-app ${selected.color}`}>{selected.code}</div><p>{selected.category.toUpperCase()}</p><h2>{selected.name}</h2><span>{selected.description}</span><div className="access-note"><b>Shared with you</b><small>You can safely open and use this project.</small></div><button className="launch-button" onClick={()=>setSelected(null)}>Launch project ↗</button></section></div>}
  </main>
}

function UserSection({title,label,action}:{title:string;label:string;action?:React.ReactNode}){return <div className="user-section-head"><div><p>{label}</p><h2>{title}</h2></div>{action}</div>}
function AppGrid({apps,toggleFavorite,setSelected}:{apps:App[];toggleFavorite:(n:string)=>void;setSelected:(a:App)=>void}){return <section className="user-app-grid">{apps.map(app=><article key={app.name}><button className={`heart ${app.favorite?'saved':''}`} onClick={()=>toggleFavorite(app.name)} aria-label={`Favourite ${app.name}`}>♥</button><div className={`large-app ${app.color}`}>{app.code}</div><p>{app.category.toUpperCase()}</p><h2>{app.name}</h2><span>{app.description}</span><button className="user-open" onClick={()=>setSelected(app)}>Open app <b>↗</b></button></article>)}</section>}
